### ISSUE TITLE
.stl Datei

### ISSUE THREAD

**Issue by Grischabock** [SoftCreatR/php-mime-detector#4]
Eine 3D .stl Datei wird nicht erkannt

**Comment by SoftCreatR** [comment]
Bitte Beispiel-Datei anhängen.

**Comment by Grischabock** [comment]
https://grischabock.ch/download/test.stl

**Comment by SoftCreatR** [comment]
Das sieht etwas komplizierter aus. Hast du noch eine weitere Testdatei für mich?

Das Problem ist, dass es mindestens 5 verschiedene Dateitypen im Format STL gibt. Aus welcher Software stammt diese? Adobe Fireworks?

**Comment by Grischabock** [comment]
Klar kein Problem

https://grischabock.ch/download/2.stl
https://grischabock.ch/download/3.stl

Das sind CAD Dateien für zb. 3D Druck. Gibt diverse Software mit der man diese öffnen kann. 
Autodesk Meshmixer, oder die Windows 10 3D App sind kostenlose Anwendungen.

**Comment by SoftCreatR** [comment]
Also sind das in diesem Fall "Stereolithography Files". Ich schaue mal, was ich tun kann.

**Comment by SoftCreatR** [comment]
Gerade mal ein wenig herumgeschaut. Auf https://www.thingiverse.com habe ich einen Haufen Dateien zum Testen gefunden. Das bringt mich allerdings nur bedingt weiter.

Was ich bisher weiß ist, dass jede "normale" STL-Datei einen 80-Byte langen Header hat. Darauf folgen 4 Bytes (Anzahl Dreiecke * 50).

Das Ganze ist im Ergebnis jedoch so generisch, dass ich keine allzu große Chance sehe, STL-Dateien von anderen Binärdateien unterscheiden zu können, ohne False-Positives zu erzeugen.

**Comment by Grischabock** [comment]
Ja das ist richtig, thingiverse ist eine der grössten Datenbanken für eine Vielzahl von CAD Dateien. 

Hört sich doch recht komplex an wenn diese sich nicht einfach zuordnen lassen.

**Comment by SoftCreatR** [comment]
Ich lasse den Issue einfach stehen. Vielleicht findet sich ja jemand mit der richtigen Idee :)
