### ISSUE TITLE
Datei wird nicht analysiert

### ISSUE THREAD

**Issue by xopez** [SoftCreatR/php-mime-detector#8]
Ok, ich kann zwar auswählen, was analysiert werden soll, er sagt kurz analizing, aber ist dann wieder bei Datei auswählen. Den Fileselect sieht man nicht auf dem Video, was im Zip ist. Aber man erkennt das "analyzing" und das danach.

[WHAT THE FILE_ - Mozilla Firefox 2018-11-05 18-25-53.zip](https://github.com/SoftCreatR/php-mime-detector/files/2549849/WHAT.THE.FILE_.-.Mozilla.Firefox.2018-11-05.18-25-53.zip)

Ist eine Jar-Datei:
Downloadlink: https://www.file-upload.net/download-13378213/gmpu.jar.html

**Comment by SoftCreatR** [comment]
Das muss an einer installierten Browser-Erweiterung liegen. Hier (FF 64.0b6) funktioniert der Upload problemlos.

Zu der Datei: Jar-Dateien sind technisch nichts anderes als Zip-Dateien. Dabei handelt es sich wiederum um eine Zip-Datei, die sich wie so viele andere Zip-Dateien nicht ohne Weiteres eindeutig identifizieren lassen. Hier müssten Parser her, allerdings ist der Mime-Detector nicht dafür konzipiert.

**Comment by xopez** [comment]
Hmmm. Habe alle Erweiterungen deaktiviert, Seite aktualisiert und das selbe in grün.
Bekomme aber in der Konsole folgendes:
```
Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/count.php. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).[Weitere Informationen]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/count.php. (Grund: CORS-Anschlag schlug fehl).[Weitere Informationen]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/upload.php. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).[Weitere Informationen]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/upload.php. (Grund: CORS-Anschlag schlug fehl).[Weitere Informationen] 
```

Firefox Version: 63.0.1

**Comment by SoftCreatR** [comment]
Kurios. Ich erhalte diese Fehler nicht und eigentlich darf den auch sonst keiner erhalten (die erste Meldung ist irrelevant).

Versuchs jetzt bitte noch einmal.

**Comment by xopez** [comment]
Die selben Fehler in der Konsole ohne Ausgabe.

**Comment by SoftCreatR** [comment]
Ich habe jetzt extra noch FF 63.0.1 nach installiert und kann das immer noch nicht reproduzieren :/

Versuchs mal bitte mit Leeren des Caches. Oder spaßeshalber im Inkognito-Modus.

**Comment by xopez** [comment]
Habe nun im Abgesicherten Modus gestartet und dort auch dort in den Inkognito gegangen.
Wieder das Gleiche.
Nur kein Stress damit :)

**Comment by xopez** [comment]
Liegt vielleicht nicht am FF.
In Edge und auch im IE klappts auch nicht.
Jetzt bin ich überfragt, System ist frisch installiert via Windows 10 komplett-Reset am 21.10.2018

Edge:
![grafik](https://user-images.githubusercontent.com/28950736/48023021-f89b1300-e13c-11e8-878c-faa17e394613.png)

**Comment by SoftCreatR** [comment]
Ich werde mal abwarten, ob sich noch wer mit denselben Problemen meldet. Danke trotzdem :)

**Comment by SoftCreatR** [comment]
Versuchs nochmal.

**Comment by SoftCreatR** [comment]
Versuchs jetzt nochmal. Der Fehler darf jetzt eigentlich nicht mehr auftreten.

EDIT:

Okay, nochmal eine Kleinigkeit geändert. Ich hoffe, es funktioniert nun. Denn wenn ich die Requests durch den Proxy jage, gibt's Probleme beim Upload größerer Dateien :/

**Comment by xopez** [comment]
Der Button öffnet nun kein Explorerfenster.
Jetzt ist irgendwas kaputt.
![grafik](https://user-images.githubusercontent.com/28950736/48025574-233c9a00-e144-11e8-995d-234d25cd7b94.png)

EDIT: Selbes im Edge.

**Comment by SoftCreatR** [comment]
Grml... Irgendwo nen Fehler ins Script gehauen... :D

**Comment by SoftCreatR** [comment]
Wird Zeit, dass ich ins Bett komme :) Bitte jetzt nochmal versuchen.

**Comment by xopez** [comment]
Nun sind wir beim unkown error :D :
![grafik](https://user-images.githubusercontent.com/28950736/48026300-f5585500-e145-11e8-8515-9085b9a4e556.png)
Habe es mit txt-File und jar versucht.
Haben aber wieder den anfänglichen Fehler:
```
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/count.php. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).[Weitere Informationen]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/count.php. (Grund: CORS-Anschlag schlug fehl).[Weitere Informationen]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/upload.php. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).[Weitere Informationen]
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://api.whatthefile.info/upload.php. (Grund: CORS-Anschlag schlug fehl).[Weitere Informationen]
```

**Comment by SoftCreatR** [comment]
Aber die Konsole ist soweit "leer"?

Ich habe eine Kleinigkeit geändert. Versuchs bitte nochmal.

Wir kriegen das heute noch hin :D Und es ärgert mich sehr, dass ich all diese Probleme nicht reproduzieren kann :(

**Comment by SoftCreatR** [comment]
> Haben aber wieder den anfänglichen Fehler:

Okay, ich bin vorerst mit meinem Latein am Ende. So sollte es eigentlich bei dir aussehen:

![image](https://user-images.githubusercontent.com/81188/48026847-81b74780-e147-11e8-828b-95c6ad23af4d.png)

Ich hab aber das Gefühl, dass zumindest der obere Teil bei dir fehlt.

**Comment by xopez** [comment]
Ok, jetzt bin ich auch verwirrt.
![grafik](https://user-images.githubusercontent.com/28950736/48027068-030eda00-e148-11e8-8599-84deb2004ae9.png)
So schauts bei mir aus.
Anfrage stimmt. Bei mir fehlt access-control-allow....
Ich versuchs mal eben im safe mode mit deaktivierten addons.

**Comment by xopez** [comment]
Hilft auch nichts

**Comment by xopez** [comment]
Die IP ist ja irgendwie auch eine ganz andere, sehe ich grade. Weiß nur nicht in wieweit es da relevant an der stelle ist.

**Comment by SoftCreatR** [comment]
Ich hätte ja jetzt gesagt, dass das irrelevant ist, jedoch würde das nicht stimmen. Ich sehe das Problem nun: Dein DNS-Cache ist veraltet. Das Ding läuft nicht mehr über Cloudflare :)

**Comment by xopez** [comment]
Gut. Dann sind wir schonmal weiter. Habe leider schon PC ausgemacht und alles drumherum. Werde ich morgen abend mal testen und mich nochmal melden. Danke schonmal :blush:

**Comment by SoftCreatR** [comment]
Vielleicht für die Zukunft: Ich habe sowohl in meiner Fritzbox, als auch bei der Netzwerkkarte selbst als DNS-Server `1.1.1.1` und `1.0.0.1` eingestellt. Damit fährst du an für sich sehr gut.

**Comment by xopez** [comment]
Habe nun DNS-Server gewechselt, da es mit dem Standartserver aus unserer FritzBox noch immer nicht klappte. Klappt nun mit dem Cloudflare-Server :D 
Fehler kam somit nicht von dir, sorry dafür.
